A few interface tweaks
computestdev/performr-runner-result-graph pull request #2
Opened 2017-11-30 17:04 UTC by botten-ct

- show full breakdown using a calculated pixelsPerMillisecond
- expand eventDetails on hover
- Add some more margin in the graph as the last '[xx] ms' was cut off
- borders a bit softer on the eyes

2017-11-30 18:47 UTC, ghost requested changes

2017-11-30 18:47 UTC, ghost commented on src/PerformrRunnerResultGraph.jsx
> +        const duration = parseInt(resultObject.getIn(['timing', 'duration']), 0);
`parseInt(foo, 0)` is intended for strings (afaik this value is already a number), and also the last argument will cause it to parse hex and octal strings. Why not use `Math.floor()`

2017-11-30 18:47 UTC, ghost commented on src/PerformrRunnerResultGraph.jsx
> +        const pixelsPerMillisecond = (screen.availWidth  - 375) / duration;
`screen.availWidth  - 375` seems like a dirty hack, which is why the linter rejects it ^^ 
Note that this graph is also used fullscreen, namely in Openrunner. Why not introduce some kind of zoom/range prop to `<PerformrRunnerResultGraph/>`?

2017-11-30 18:47 UTC, jvanderwel-ct commented on src/components/style/EventPlotItem.scss
> +            -moz-box-shadow: inset -8px -8px 6px -6px  rgba(0,0,0,0.33), inset -8px 8px 6px -6px  rgba(0,0,0,0.26);
Are those vendor prefixes still needed? I suspect browsers that old will not be able to render this project for many other reasons.

2017-11-30 19:04 UTC, botten-ct commented on src/PerformrRunnerResultGraph.jsx
> +        const pixelsPerMillisecond = (screen.availWidth  - 375) / duration;
1. We do need the available width to calculate the pixelsPerMillisecond so the full breakdown is shown (as requested by stakeholder). This is exactly what we needed afaik.

2. Cause we implement changes incremental.

2017-11-30 22:58 UTC, jvanderwel-ct commented on src/PerformrRunnerResultGraph.jsx
> +        const pixelsPerMillisecond = (screen.availWidth  - 375) / duration;
Sure, but we have to make sure it also works properly in Openrunner. Which is a more important use case at the moment.
Would everything break, or would we just see white space?

2017-12-01 11:13 UTC, jvanderwel-ct commented
Merged https://github.com/computestdev/performr-runner-result-graph/commit/ca6756b50cd7f4bfc0577a9c0f22cdfed00720c7

2017-12-01 11:13 UTC, closed without merging